### ISSUE TITLE
KDE integration: kde openDialog can't select folder

### ISSUE THREAD

**Issue by Alexqwesa** [flathub/io.dbeaver.DBeaverCommunity#110]
I had install DBeaver from flatpak, 
but then i tried to open any folder(any openDialog that required folder as target, for example - open project, or import project)
it show KDE openDialog, which can't select anything...

**Comment by Eonfge** [comment]
Sorry for asking this late... but is this still an issue? 

If so, can you tell me which distribution and KDE you're using?

**Comment by Alexqwesa** [comment]
it was long time ago, i update KDE, DBeavear and everything else - don't have this problem anymore
