### ISSUE TITLE
Permission denied while converting private key for SSH access

### ISSUE THREAD

**Issue by jnko266** [flathub/io.dbeaver.DBeaverCommunity#115]
I'm trying to access a remote DB over SSH using the same configuration as on my work Linux machine. On my home machine 
(macOS Monterey 12.0.1) however, when I try to connect, I get permission denied for writing the PEM key to "/var/folders/n_/d00tfnp50t5d6b3w6nldfv480000gn/T/.dbeaver-temp16068457393514091629/mariaDB-17dc2e28cd5-6058cae4d0e392bd.pem". I tried manually changing permissions using _chmod_, but even with sudo, I get permission denied on the _chmod_. 
DBeaver version 21.3.1.202112130652. 
Any help would be much appreciated!
![dbeaver](https://user-images.githubusercontent.com/33516559/146769334-38eeee14-b765-4f81-9aec-14e8afd30bb0.jpg)

**Comment by dac73** [comment]
@jnko266 are you sure you are using the Flatpak version on the MacOs?
Anyway, this repo is just Flatpak packaging, project repo is here: https://github.com/dbeaver/dbeaver
:wink:
