### ISSUE TITLE
can not show schema and tables when connecting sparksql

### ISSUE THREAD

**Issue by wonb168** [flathub/io.dbeaver.DBeaverCommunity#12]
only default database can show, but no tables in it, left navigator.
but in sql, show databases or show tables is ok,all databases and tables can query,why?

**Comment by krashekspres** [comment]
Is this Flatpak only issue?

**Comment by serge-rider** [comment]
It is not related to Flatpak.
Is is tracked here: https://github.com/dbeaver/dbeaver/issues/5314 (we need some assistance).
