### ISSUE TITLE
Missing icon on KDE Plasma

### ISSUE THREAD

**Issue by shakeelansari63** [flathub/io.dbeaver.DBeaverCommunity#121]
Hello When I open DBeaver Flatpak version on KDE Plasma, it shows the right DBeaver icon during splash screen. But when app launches, its icon is lost.

During Splash Window --
![image](https://user-images.githubusercontent.com/8319053/152494278-4658cdf8-214b-4a7c-83d5-5786034727be.png)

When App Launches -- 
![image](https://user-images.githubusercontent.com/8319053/152493964-ea7596e2-1d94-4080-a81f-be84395ab555.png)

**Comment by shakeelansari63** [comment]
Looks like this is fixed in version 21.3.4 but the icon which is showing is generic and not honouring the current theme icon pack. 

Though I have io.dbeaver.DBeaverCommunity.svg in my Icon pack, it does not show use that icon.

**Comment by dac73** [comment]
I don't have Plasma at my disposal. On Gnome, everything works perfectly. Try to ask for help from the KDE community. I know they have generic icon problems with more apps, not just dbeaver.

**Comment by shakeelansari63** [comment]
Fixed automatically after upgrading to v21.3.4 and system restart. Good to close this issue.
