### ISSUE TITLE
Add a new maintainer

### ISSUE THREAD

**Issue by dac73** [flathub/io.dbeaver.DBeaverCommunity#142]
Not sure what's the process, so opening an issue :)
Can we add [@Eonfge](https://github.com/Eonfge) as a maintainer here? 
Context: https://github.com/flathub/io.dbeaver.DBeaverCommunity/pull/141#issuecomment-1241597836

**Comment by bilelmoussaoui** [comment]
Invited

**Comment by Eonfge** [comment]
![giphy-downsized-large-394232708](https://user-images.githubusercontent.com/33983090/189344695-c46f9317-3e65-4759-ad5c-fd503e587481.gif)
