### ISSUE TITLE
Update to 22.2.2

### ISSUE THREAD

**Issue by hutchhicken** [flathub/io.dbeaver.DBeaverCommunity#145]
It looks like DBeaver says 22.2.2 is available, but Flatpak hasn't updated yet.

**Comment by Eonfge** [comment]
I've published the update, but sometimes it takes a day before it actually goes online. This is because of all the CDNs and complex pipelines behind the scenes. 

Can you check again if DBeaver 22.2.2 is available for you?

**Comment by dac73** [comment]
@Eonfge I think flathub does master builds once per day. But when needed, you can push a new build "ASAP" from here: https://buildbot.flathub.org/#/apps/io.dbeaver.DBeaverCommunity (you should be able to log in with your GitHub account and have correct permissions).

**Comment by Eonfge** [comment]
@dac73 I normally do that, but even then it's dependent on the network and the different CDNs. Customers from China or Russia have different servers from different companies, compared to Europeans or Americans
