### ISSUE TITLE
GNOME Shell Crashes When Reorganizing Tabs

### ISSUE THREAD

**Issue by aliasbody** [flathub/io.dbeaver.DBeaverCommunity#268]
### Description:
I am experiencing a GNOME Shell crash when using DBeaver Community Edition installed via Flatpak. The issue occurs specifically when I open two or more tabs from the same database but with different tables, and then try to move one of the tabs to reorganize them. This results in an immediate crash of GNOME Shell.

### Steps to Reproduce:

- Open DBeaver
- Connect to a database and open two or more tabs with different tables from the same database.
- Attempt to drag and move one of the tabs to a different position to reorganize.
- Observe GNOME Shell crashing immediately.

### Expected Behavior:
DBeaver should allow tabs to be reorganized without causing GNOME Shell to crash.

### Actual Behavior:
Reorganizing tabs in DBeaver causes an immediate crash of GNOME Shell, disrupting the entire desktop environment.

### System Information:
**OS:** Fedora 40
**Kernel Version:** 6.8.9-300.fc40.x86_64
**DBeaver Version:** 24.0.4.202405051837
**Installation Method:** Flatpak/Flathub
**GNOME Shell Version:** 46.1
**Mutter Version:** 46.1
**Java Version:** 21.0.3 by Flathub (64bit)

### Additional Information:
**The issue doesn't happen on Xorg, only on Wayland**

Here are some relevant logs from journalctl when the crash occurs:

    [30554.433527] gnome-shell[2558]: segfault at 190 ip 00007f0c3216928d sp 00007ffcd0f44030 error 4 in libmutter-14.so.0.0.0[7f0c3203f000+17b000] likely on CPU 7 (core 9, socket 0)

And when debugging the flatpak app (with log):

    Gdk-Message: 19:20:02.710: Error reading events from display: Ligação reposta pelo peer

### Steps Taken to Troubleshoot:
- Updated all packages and Flatpak applications to the latest versions.
- Disabled all GNOME Shell extensions to rule out conflicts.
- Reinstalled DBeaver and GNOME Shell.

**Comment by Eonfge** [comment]
Reproduced with the non-sandboxed version, so I've created an issue with the DBeaver team. For the record, I'm not affiliated with DBeaver Corporation.

**Comment by Eonfge** [comment]
Reported with the GNOME Shell team: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7658

**Comment by pcdavid** [comment]
FYI, it's been fixed on main for a little while (see https://gitlab.gnome.org/GNOME/mutter/-/issues/3462) but not yet reported on the gnome-46 maintenance branch (AFAICT).

**Comment by Eonfge** [comment]
Confirmed fixed with the latest version of Mutter.

**Comment by aliasbody** [comment]
Can confirm it doesn't happen anymore.
