### ISSUE TITLE
Icon doesn't appear in GNOME menu

### ISSUE THREAD

**Issue by wolfmanfp** [flathub/io.dbeaver.DBeaverCommunity#272]
I use GNOME 46 on Ubuntu 24.04. For some reason DBeaver doesn't show up in the menu. I checked it in MenuLibre, it isn't set as hidden.

**Comment by Eonfge** [comment]
I have no clue. could you tell me what you see when you do 
```
flatpak list | grep dbeaver
```

**Comment by Eonfge** [comment]
Mmh. First I though you might have had a test-version, but that's not the case. I'll have to look into this and see if I can reproduce it

**Comment by wolfmanfp** [comment]
I think I figured it out: an application doesn't appear in the menu if it's pinned to the dash. Now I feel like an idiot :man_facepalming:

**Comment by Eonfge** [comment]
No shame, we all have our moments :man_shrugging:
