### ISSUE TITLE
Screenshots not representative 

### ISSUE THREAD

**Issue by Eonfge** [flathub/io.dbeaver.DBeaverCommunity#34]
I hate to be that guy, but your screenshots are quite far off from the actual project. You're using screenshots made on Windows and Mac, with fonts and UI toolkits not available on Linux.

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

It would be better to replace the images with images more representative of the Linux version.

**Comment by krashekspres** [comment]
I completely agree with you, screenshots are pulled from https://github.com/dbeaver/dbeaver 

I suppose we could create new screenshots and host them in this repo. So if anyone is able/willing to add new screenshots, I will gladly incorporate them into the manifest file.

**Comment by Eonfge** [comment]
![Screenshot from 2019-09-10 13-54-03](https://user-images.githubusercontent.com/33983090/64611886-c00a3c80-d3d2-11e9-9504-9c7f581d98e1.png)
![Screenshot from 2019-09-10 13-52-56](https://user-images.githubusercontent.com/33983090/64611887-c0a2d300-d3d2-11e9-812f-e1ddd34be684.png)
![Screenshot from 2019-09-10 13-52-14](https://user-images.githubusercontent.com/33983090/64611889-c0a2d300-d3d2-11e9-8af7-779da15d4d38.png)

I did discover another bug while making these images. The application looks like shit when you use awaita-dark:

![Screenshot from 2019-09-10 13-57-19](https://user-images.githubusercontent.com/33983090/64611987-03fd4180-d3d3-11e9-8d77-263472e3feea.png)


 For the time being, I would recommend you to add the following setting to the finalize arguments:
```
--env=GTK_THEME=Adwaita:light
```

**Comment by p1u3o** [comment]
I'm not sure why, but this is how it looks like for me on Adwaita-dark.

![image](https://user-images.githubusercontent.com/38067056/64876776-d5d46780-d647-11e9-9c75-d19f298c343b.png)

**Comment by krashekspres** [comment]
For me, it was also broken on stock Fedora 30. So yeah, I don't know.

**Comment by p1u3o** [comment]
After some quick testing, disabling theming in the Settings makes it properly inherit the GTK stylesheet.

But it's probably safer just to enforce Adwaita light.

**Comment by krashekspres** [comment]
Looks like it, but I don't like to enforce this kind of stuff to users.

@serge-rider currently I'm enforcing Adwaita:light via .desktop file. Is there a way to disable theming in app instead, so GTK theming works out of the box?

**Comment by p1u3o** [comment]
It might be worth checking how it looks under different GTK themes, as I don't think Eclipse is tested thoroughly against anything else but Adwaita (which is why it looks perfect under Adwaita).

**Comment by Eonfge** [comment]
@krashekspres To change the behaviour of an app, you'll have to look at the code and itself, as this is no longer within the domain of Flatpakking. There might be an env-variable for allowing theming, or you mightbe able to create an alternative base settings which disable theming.

Either way, for the time being I would keep the env= parameter until we have something that works consistently for users.

**Comment by krashekspres** [comment]
@Eonfge I know, that's why I mentioned @serge-rider, he's a maintainer of the upstream app.

**Comment by dac73** [comment]
Closing this since screenshots were changed. Will follow the theming issue in dbeaver repo.
