### ISSUE TITLE
Local client not found

### ISSUE THREAD

**Issue by laurentiumagureanu** [flathub/io.dbeaver.DBeaverCommunity#44]
When trying to import a database I get a **local client** related error
![image](https://user-images.githubusercontent.com/6639076/69498248-399fca00-0eee-11ea-97ea-9add5326143d.png)

I think there is an issue with permissions since I cannot edit them and it seems that built-in permissions only provide access to Home

![image](https://user-images.githubusercontent.com/6639076/69498265-7370d080-0eee-11ea-8cb9-c9a57df5200c.png)

**Comment by p1u3o** [comment]
Can you install 'io.dbeaver.DBeaverCommunity.Client.mariadb' and see if you get the same error?

**Comment by laurentiumagureanu** [comment]
It works with the additional package installed. Another workaround is to copy all the mysql/mariadb client related binaries to a location in the $HOME directory.

I'll close this now

**Comment by p1u3o** [comment]
> Another workaround is to copy all the mysql/mariadb client related binaries to a location in the $HOME directory.

Probably not the best idea because these may not be compiled against the same libraries available in the Flatpak runtime, where as the extension is.

But glad it's all resolved.
