### ISSUE TITLE
Changes list not showed correctly

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/io.dbeaver.DBeaverCommunity#57]
![2020-06-07_04-12](https://user-images.githubusercontent.com/56733813/83959476-30b48b80-a875-11ea-86a6-1ba6cd780b6b.png)

**Comment by EchedeyLR** [comment]
Oops. A faulty explanation.

The first arrow it's because it seems a warning or additional notification that use to start the changes list and not part of the list itself.

**Comment by dac73** [comment]
I think this should be filed against flathub web?
If you look in XML, identation is added: https://github.com/flathub/io.dbeaver.DBeaverCommunity/blob/master/io.dbeaver.DBeaverCommunity.appdata.xml

**Comment by EchedeyLR** [comment]
If some main contributor can move the issue to avoid making a new one, woud be great.

**Comment by dac73** [comment]
Sorry, edited post, this can be achived here also, looks like they just trim the elements, so space idents isn't gonna work.

**Comment by EchedeyLR** [comment]
Don't worry. I also checked the file just know.

You are right. The list intems after a head item finishing in colons should be nested in other unordered list.

**Comment by EchedeyLR** [comment]
What happened here?:
![Screenshot_20200622-192227](https://user-images.githubusercontent.com/56733813/85322221-dd217f00-b4bd-11ea-9a37-bb80e1881c41.png)

**Comment by dac73** [comment]
Flathub doesn't allow more than 15 paragraphs. We can either merge paragraphs or trim changes.
I will check with next update if I can do this better.
