### ISSUE TITLE
Can't configure DBeaver to use local client from /app/clients

### ISSUE THREAD

**Issue by lbssousa** [flathub/io.dbeaver.DBeaverCommunity#58]
I have both `io.dbeaver.DBeaverCommunity` and `io.dbeaver.DBeaverCommunity.Client.pgsql` in my Fedora Silverblue 32. I want to configure a new PostgreSQL connection in DBeaver and set pgsql **Local Client**.

I've read several issues here suggesting I should select `/app/clients` folder under **Local Client**, but I'm unable find it when I click on **Add Home** button. The only workaround I've found is selecting folder `/var/lib/flatpak/runtime/io.dbeaver.DBeaverCommunity.Client.pgsql/x86_64/stable/active/files` under **Add Home** dialog.

Is this the correct way?

**Comment by dac73** [comment]
I have just tested this with installed both extensions for pgsql and DBeaver in flatpak. The client was found under `/app/clients`.
![Screenshot_20200706_202438](https://user-images.githubusercontent.com/20690019/86626261-be93ab80-bfc6-11ea-96a2-bf4cfbdbe568.png)

If your workaround works, then use it, it points to same files just by using absolute path (this might break in future when/if we remove `$HOME` access to DBeaver in flatpak).

**Comment by lbssousa** [comment]
Hmm... Now I'm curious. Based on your screenshot, I can assume you're using KDE Plasma. I'm using Fedora Silverblue 32, with GNOME Desktop. Could this be a divergence between xdg-desktop-portal-kde and xdg-desktop-portal-gtk behaviours?

**Comment by dac73** [comment]
It shouldn't be, and also it worked for me on Gnome on Fedora when we first added extensions.
