### ISSUE TITLE
Can't use system MySQL binary

### ISSUE THREAD

**Issue by EvanWashkow** [flathub/io.dbeaver.DBeaverCommunity#8]
I've tried setting the "Local Client" setting to `/var/run/host/usr/bin/mysql`, after installing MariaDB locally. This setting works completely fine in Visual Studio Code for pointing to PHP. However, it does not work in DBeaver.

As such, I cannot import / export from the database.

**Comment by krashekspres** [comment]
That is generally a bad idea, only thing exposed to DBeaver is $HOME and I would even like to narrow that one just to documents. Can't you use DBeaver internal driver?
Other workaround solution would be to copy binaries to a folder somewhere inside $HOME and change MySQL home to it from DBeaver.

I think the right solution would be to either install MySQL inside the sandbox or create Flatpak plugin for each DB driver which you could connect to DBeaver flatpak.  I would rather go with the second solution as we don't want to increase the size of the base app.

Anyway, this task is currently too big for my free time, so if anyone else wants to tackle it, go for it.

**Comment by EvanWashkow** [comment]
> Can't you use DBeaver internal driver?

See, exactly. I was always super confused why DBeaver requires the MySQL binary when it is installing its own drivers on setup. I'd rather use those drivers than copying bins from the system directory: is there anyway I can do that? (They appear to be Java archives).

**Comment by p1u3o** [comment]
A solution to this would be to use the Flatpak extension system.

```
      "add-extensions": {
        "io.dbeaver.DBeaverCommunity.Client": {
          "version": "6",
          "directory": "clients",
          "add-ld-path": "lib",
          "merge-dirs": "bin",
          "subdirectories": true,
          "no-autodownload": true,
          "autodelete": true
        }
      },
````

Then you'd create a flatpak extension e.g. `io.dbeaver.DBeaverCommunity.Client.mariadb` that builds and installs the client, Flatpak can then merge the relevant /bin directories making them available in /app/clients/bin for use, such as mysql and mysqldump

I've been able to get it working locally, but my mariadb extension ends up being 1.3GB which is far from ideal so I need to clean that up.

**Comment by krashekspres** [comment]
@p1u3o do you want to own this issue, it looks like you are already halfway there?

**Comment by p1u3o** [comment]
@krashekspres 

Sure, I'll let you know how I get on.

I'm guessing you're good using the extension system going forward for this?

**Comment by krashekspres** [comment]
looks like the correct way of achieving this, sure

**Comment by p1u3o** [comment]
https://github.com/p1u3o/io.dbeaver.DBeaverCommunity.Client.mariadb
https://github.com/p1u3o/io.dbeaver.DBeaverCommunity/tree/flatpak_extensions

These should work. 
The mariadb extension now sits at ~100MB, as I've got it to just compile what we need. You'll still have to set the path in the driver to /app/clients, but I've added it to the PATH.

![Screenshot from 2019-06-05 19-39-31](https://user-images.githubusercontent.com/38067056/58981150-b8cb0580-87c9-11e9-9037-3fe9a152f600.png)

**Comment by Sarke** [comment]
@krashekspres until these build properly, can we re-open this issue?

https://github.com/flathub/flathub/pull/1030
https://github.com/flathub/flathub/pull/1031

Not sure if there are other ways to install these.  Some documentation on how to add them (or just a mention that they exist) would be useful.

**Comment by krashekspres** [comment]
Sure, it was supposed to be done in a day or two after merging here. But I had serious lack of time :)

**Comment by krashekspres** [comment]
The latest build was successful (looks like it was bot bad day last time :) )
If you want you can test this before flathub maintainers push this into the store by running:
`flatpak install --user https://dl.flathub.org/build-repo/4635/io.dbeaver.DBeaverCommunity.Client.mariadb.flatpakref`

**Comment by Sarke** [comment]
`error: Can't load uri https://dl.flathub.org/build-repo/4635/io.dbeaver.DBeaverCommunity.Client.mariadb.flatpakref: Server returned status 404: Not Found`

**Comment by Sarke** [comment]
Not sure it built properly, shows an error here:

https://flathub.org/builds/#/builders/39/builds/587/steps/13/logs/stdio

**Comment by krashekspres** [comment]
Those should be just warnings (appdata is according to freedesktop spec).
Perhaps there is something with bot again, will try to figure out.

**Comment by krashekspres** [comment]
Add-ons available in SW center.

**Comment by davidrhoderick** [comment]
So I just switched to this package from the Debian apt version, which was working fine but never updated to latest version.  I cannot get mysqldump to work even after following these steps.  Do I need to update the MySQL driver to a MariaDB one in order for these to work?  What about older versions of MySQL; should this MariaDB extension work with those?

**Comment by dac73** [comment]
We don't have MySQL extension (feel free to add it if you want, you can use existing blueprint from maria).
That being said you might also use local binary if you move it to a location that is accessible to DBeaver (currently DBeaver has access to entire $HOME) or add permissions to DBeaver via `flatpak override` to the location of your binary (do understand that you are allowing DBeaver access to that part of the filesystem). 

Disclaimer: Didn't test any of the workarounds but in theory, they should work.

**Comment by netdragonboberb** [comment]
Install flatseal as described here https://github.com/dbeaver/dbeaver/issues/5008
