### ISSUE TITLE
bump runtime/sdk to GNOME Application Platform version 40

### ISSUE THREAD

**Issue by mess-maker** [flathub/io.dbeaver.DBeaverCommunity#87]

**Comment by henkesteen** [comment]
I got this warning today when I checked for updates

`Info: org.gnome.Platform//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   io.dbeaver.DBeaverCommunity`

Do you have any estimate on this?

**Comment by dac73** [comment]
Closed in #101
